spring:
    application:
        name: myapp
    profiles:
        active: local

logging:
    level:
        '[com.sk.skala.myapp.controller]': DEBUG
        '[com.sk.skala.myapp.service]': DEBUG

springdoc:
    api-docs:
        path: /api-docs
        enabled: true
    swagger-ui:
        path: /swagger-ui.html
        enabled: true
        operations-sorter: alpha
        tags-sorter: alpha
        display-request-duration: true
        try-it-out-enabled: true
    show-actuator: false

management:
    server:
        port: 8080 # Actuator 포트 설정 (실무에서는 일반적으로 서비스용과 관리용 포트를 분리함)
    endpoints:
        web:
            exposure:
                include: "*" # Prometheus endpoint 노출
    endpoint:  # 쿠버네티스 전용으로 만든 설정??
        health:
            probes:
                enabled: true # LivenessState, ReadinessState 활성화
    health:
        livenessState:
            enabled: true # LivenessState 활성화
        readinessState:
            enabled: true # ReadinessState 활성화
    metrics:
        enable:
            all: true # 모든 기본 메트릭 활성화

spec:
    containers:
        - name: my-spring-app
          image: my-registry.com/my-spring-app:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
                path: /actuator/health/liveness
                port: 8081
            initialDelaySeconds: 5 # 컨테이너 시작 후 5초 뒤 체크 시작
            periodSeconds: 10 # 10초마다 체크
            timeoutSeconds: 3 # 응답 없으면 3초 후 실패 간주
            failureThreshold: 3 # 3번 연속 실패 시 컨테이너 재시작
          readinessProbe:
            httpGet:
                path: /actuator/health/readiness
                port: 8081
            initialDelaySeconds: 5 # 컨테이너 시작 후 5초 뒤 체크 시작
            periodSeconds: 10 # 10초마다 체크
            timeoutSeconds: 3 # 응답 없으면 3초 후 실패 간주
            failureThreshold: 3 # 3번 연속 실패 시 트래픽에서 제외
